### ISSUE TITLE
several errors at inference time

### ISSUE THREAD

**Issue by ChanYeongShin** [MartinPernus/MaskFaceGAN#6]
Thanks for powerful facial editing method. I followed your setup and instructions. But I got a different image between your output reported image and several errors at inference time. 

1. I didn't change any code and ran program by `python main.py --attribute mouth_slightly_open --outdir output --image input/1815.jpg`, but i got different result image as below. (First image is my result, Second image is reported result)![1815-mouth_slightly_open](https://user-images.githubusercontent.com/38932333/196111064-e44b3893-19d4-435c-a364-2cb6d51921ee.jpg)
![1815-mouth_slightly_open_2](https://user-images.githubusercontent.com/38932333/196111085-8005857a-bb25-44ac-baad-2abf8d714052.jpg)

2. I want to change other local attributes (ex. hair color), however i got a error as
 below. 
![1](https://user-images.githubusercontent.com/38932333/196111482-44377b1e-8602-4a55-b436-a9de369b05ee.png)

3. I try to change same attributes with other image (ex. donald_trump.jpg), but i got really poor result. Can you explain why i get these poor image..
![donald_trump-mouth_slightly_open](https://user-images.githubusercontent.com/38932333/196111804-0483b4a2-08c1-465a-9471-8c6318258c16.jpg)
![donald_trump](https://user-images.githubusercontent.com/38932333/196111812-a7365415-3e78-4a91-8268-94d0b9a1214d.jpg)

I hope that you reply to me.
Sincerely yours.

**Comment by MartinPernus** [comment]
Hey,

Thank you for the interest!

Regarding the first two issues; fixed the bug in c8644ab1022fa36dbc89f70e309f4d4df8ad3a33.

I tried some editing examples on Trump with varying success - the face seems to be pretty hard to embed in StyleGAN. No examples were as bad as yours though, I guess the issue was covered by the bug mentioned above. 

Anyway, I added an additional blending option 'no_skin', which only blends in the final target region, which is much preferable for hard to embed face such as Trump's. The result for 'brown hair' editing with options `--e4e_init --blend_option no_skin` produces something this:
![trump-brown_hair](https://user-images.githubusercontent.com/36865527/196191022-cc43e502-7fb3-4bca-8cc7-bc7f9b0e9945.jpg).

Some visual artifacts are present, playing with number of iterations should help; consider increasing steps.latent in config.yml to achieve better results.

Best,
Martin
